package classes;

import java.io.Serializable;
import java.io.File;
import java.util.Calendar;
import java.util.ArrayList;
import java.text.SimpleDateFormat;

/**
 * Photo is an object that holds the actual
 * image and the various information about
 * it: Time and Date, tags, etc
 * 
 * @author Samuel Uganiza
 * @author Nicholas Petriello
 */
public class Photo implements Serializable{
	
	/**
	 * Autogenerated serial number
	 */
	private static final long serialVersionUID = 3063382592784005045L;

	private ArrayList<Tag> tags;
	private String date;
	private String name;
	private String filePath;
	private String caption;
	
	public Photo(String filePath){
		
		File f = new File(filePath);

		Calendar c = Calendar.getInstance();
		c.setTimeInMillis(f.lastModified());
		SimpleDateFormat format = new SimpleDateFormat("MM-dd-yyyy");
		
		this.tags = new ArrayList<Tag>();
		this.date = format.format(c.getTime());
		this.name = UserList.removeExtension(f.getName());
		this.filePath = filePath;
		this.caption = "";
	}
	
	@Override
	public String toString() {
		return this.name;
	}
	
	/**
	 * addTag() inserts a given addTag into the tags
	 * list of a Photo
	 * @param addTag Tag to be added to the Photo's tag list
	 * @return true if the add was successful, false otherwise
	 */
	public boolean addTag(Tag addTag){
		
		if(this.tags.contains(addTag))
			return false;
		else
			this.tags.contains(addTag);
			return true;
		
	}
	
	/**
	 * deletTag() finds the tag and deletes it, if its in the list.
	 * @param delTag The tag String to be deleted
	 * @return true if it was removed; false otherwise
	 */
	public boolean deleteTag(Tag delTag){
		
		return this.tags.remove(delTag);
		
	}
	
	public ArrayList<Tag> getTags(){
		
		return this.tags;
	}
	
	public String getDate(){
		
		return this.date;
	}
	
	public String getName(){
		
		return this.name;
		
	}
	
	public String getFilePath() {
		return this.filePath;
	}
	
	public void setCaption(String newCap){
		
		this.caption = newCap;
		
	}
	
	public String getCaption(){
		
		return this.caption;
		
	}
	
}


