package classes;

import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.io.Serializable;
import java.util.Calendar;
import java.util.ArrayList;

/**
 * Photo is an object that holds the actual
 * image and the various information about
 * it: Time and Date, tags, etc
 * 
 * @author Samuel Uganiza
 * @author Nicholas Petriello
 */
public class Photo implements Serializable{
	
	/**
	 * Autogenerated serial number
	 */
	private static final long serialVersionUID = 3063382592784005045L;
	
	// holds list of photos
	public static ArrayList<Photo> masterPhotoList;
	
	private static boolean DEBUG = true;
	
	private ArrayList<Tag> tags;
	private Calendar date;
	private String name;
	
	// reference to index on master photo list
	private int index;
	
	public Photo(Calendar photoDate, String photoName, int index){
		
		this.tags = new ArrayList<Tag>();
		this.date = photoDate;
		this.name = photoName;
		this.index = index;
	}
	
	/**
	 * addTag() inserts a given addTag into the tags
	 * list of a Photo
	 * @param addTag Tag to be added to the Photo's tag list
	 * @return true if the add was successful, false otherwise
	 */
	boolean addTag(Tag addTag){
		
		if(this.tags.contains(addTag))
			return false;
		else
			this.tags.contains(addTag);
			return true;
		
	}
	
	/**
	 * deletTag() finds the tag and deletes it, if its in the list.
	 * @param delTag The tag String to be deleted
	 * @return true if it was removed; false otherwise
	 */
	boolean deleteTag(Tag delTag){
		
		return this.tags.remove(delTag);
		
	}
	
	ArrayList<Tag> getTags(){
		
		return this.tags;
	}
	
	Calendar getDate(){
		
		return this.date;
	}
	
	String getName(){
		
		return this.name;
		
	}
	
	// TODO: add getIndex()
	
	/**
	 * Instantiates the master photo list from an existing user database ser file 
	 * by deserializing the information from photos.ser if it finds it.
	 */
	@SuppressWarnings("unchecked")
	public static void readFromDatabase() {
		try {
			ObjectInputStream in = new ObjectInputStream(new FileInputStream("data/photos.ser"));
			Object data = in.readObject();
			if(data instanceof ArrayList<?>) {
				ArrayList<?> arr = (ArrayList<?>)data;
				if(!arr.isEmpty() && arr.get(0) instanceof Photo) {
					masterPhotoList = (ArrayList<Photo>)arr;
				}
			}
			in.close();
			if(DEBUG) System.out.println("Sucessfully read from photo database.");
		} catch (IOException e) {
			if(DEBUG) System.out.println("Photo database not found, creating new one.");
			// first time read, if not found then create a new file.
			masterPhotoList = new ArrayList<Photo>();
			writeToDatabase();
		} catch (ClassNotFoundException c) {
			if(DEBUG) System.out.println("ArrayList class not found");
			c.printStackTrace();
		}
	}

	/**
	 * Updates the photo database text file by writing the current list into a
	 * ser file after every add.
	 */
	public static void writeToDatabase() {
		try{
			ObjectOutputStream out = new ObjectOutputStream(new FileOutputStream("data/photos.ser"));
			out.writeObject(masterPhotoList);
			out.close();
			if(DEBUG) System.out.println("Success writing to photo database.");
		} catch(IOException e) {
			if(DEBUG) System.out.println("IO error with photo database.");
			e.printStackTrace();
		}
	}

}


