package classes;

import java.io.Serializable;

/**
 * Tag object stores two strings that are ascribed 
 * to each picture as per the user
 * 
 * @author Nicholas Petriello
 *
 */
public class Tag implements Serializable{

	/**
	 * Autogenerated serial number
	 */
	private static final long serialVersionUID = 8216510983416262539L;
	
	private String name;
	private String value;
	
	/**
	 * The Tag takes in two string to be created
	 * 
	 * @param tagName This is name of the Tag
	 * @param tagValue This is the value of the Tag
	 */
	public Tag(String tagName, String tagValue){
		
		this.name = tagName;
		this.value = tagValue;
		
	}
	
	/**
	 * compareTo() is just to find a exact matching
	 * Tag
	 * 
	 * @param compare The Tag to be compared with
	 * @return int showing how similar to the caller Tag
	 * is to compare. 0 = equal.
	 */
	public int compareTo(Tag compare){
		
		return this.name.compareTo(compare.name) + 
				this.value.compareTo(compare.value);
		
	}
	
	/**
	 * compareNames() does what {@link #compareTo(Tag)}
	 * does but restricts the comparison to the names
	 * of the Tags.
	 * 
	 * @param compare The Tag whose name is to be compared
	 * with
	 * @return int showing how similar to the caller Tag
	 * is to compare. 0 = equal.
	 */
	public int compareNames(Tag compare){
		
		return this.name.compareTo(compare.name);
		
	}
	
	/**
	 * compareValues() does what {@link #compareTo(Tag)}
	 * does but restricts the comparison to the values of the
	 * Tags.
	 * @param compare The Tag whose value is to be compared with
	 * @return int showing how similar to the caller Tag 
	 * is to compare. 0 = equal.
	 */
	public int compareValues(Tag compare){
		
		return this.value.compareTo(compare.value);
		
	}
	
	public String getTagName(){
		return this.name;
	}
	
	public String getTagValue(){
		return this.value;
	}
	
	
		
	
}
