package classes;

import java.io.Serializable;
import java.util.ArrayList;

/**
 * User class defines the User object that appears on the list
 * in the admin screen. Holds a name, a pass, and an extendable
 * list of albums. This class also holds a global list of Users
 * for reference in the AdminController class.
 * 
 * @author Nicholas Petriello
 * @author Samuel Uganiza
 *
 */
public class User implements Serializable{

	/**
	 * Autogenerated serial number.
	 */
	private static final long serialVersionUID = 7089640660698420983L;

	/**
	 * User object's username, password, and list of references to different albums.
	 */
	private String name;
	private String pass;
	private ArrayList<Album> albums;
	
	/**
	 * List of photo references for this user.
	 */
	private ArrayList<Photo> photosPool;

	/**
	 * User constructor. Takes name and pass, instantiates
	 * private list of albums to be empty.
	 * 
	 * @param name Name of user
	 * @param pass Chosen password
	 */
	public User(String name, String pass) {
		this.name = name;
		this.pass = pass;
		this.albums = new ArrayList<Album>();
		this.photosPool = new ArrayList<Photo>();
	}

	/**
	 * toString override to print username and password of selected user
	 * 
	 * @return String containing user's username and password
	 */
	@Override
	public String toString() {
		return this.name + " " + this.pass;
	}
	
	/**
	 * Returns name of user.
	 * 
	 * @return name
	 */
	public String getName() {
		return this.name;
	}

	/**
	 * Returns pass of user.
	 * 
	 * @return pass
	 */
	public String getPass() {
		return this.pass;
	}

	/**
	 * Returns list of albums of user.
	 * 
	 * @return albums
	 */
	public ArrayList<Album> getAlbums(){
		return this.albums;
	}
	
	public ArrayList<Photo> getPhotosPool(){
		return this.photosPool;
	}
	
	/**
	 * Attempts to add a photo to the master photo list. If it finds a duplicate by file
	 * path, return the index at which it exists in the master photo list. Otherwise,
	 * return the last index to indicate that it has been added.
	 * 
	 * @param photo The photo to add
	 * @return The index in reference to the master photo list
	 */
	public int checkInPhotos(Photo photo) {
		
		// check for duplicates
		for(int i = 0; i < this.photosPool.size(); i++) {
			if(this.photosPool.get(i).getFilePath().equals(photo.getFilePath())) {
				return i;
			}
		}
		
		// otherwise add it
		this.photosPool.add(photo);
		return this.photosPool.size() - 1;
	}
	
	/**
	 * Attempts to delete a photo from the master photo list. If it finds that another
	 * album still keeps a reference to this photo, the photo will not be removed.
	 * Otherwise, if it is the only album to contain the photo, the photo will then be
	 * deleted from the master photo list.
	 * 
	 * @param photo
	 */
	public void deletePhoto(Photo photo) {
		
		// check all albums in this user to see if any more albums have same reference to photo
		int i = 0;
		for(Album a : this.albums) {
			for(Photo p : a.getPhotos()) {
				if(p.getFilePath().equals(photo.getFilePath())) {
					i++;
				}
			}
		}
		
		// if it not found anywhere else, delete it
		if(i > 1) {
			if(UserList.DEBUG) System.out.println("File found in other albums, did not delete from pool.");
		} else {
			this.photosPool.remove(photo);
			if(UserList.DEBUG) System.out.println("Deleted " + photo.getName() + " from " + this.getName() + "'s pool.");
		}
	}

}
